---
title: "Class13"
author: "Kellie Lemoine"
date: "May 15, 2019"
output: html_document
---

# Ensemble

What proportion of the Mexican Ancestry in Los Angeles sample population (MXL)
are homozygous for the asthma associated SNP (G|G)? 

```{r}
mxl <- read.csv("373531-SampleGenotypes-Homo_sapiens_Variation_Sample_rs8067378.csv")
```

```{r}
table(mxl$Genotype..forward.strand.)
```

```{r}
# proportion
round((table(mxl$Genotype..forward.strand.)/nrow(mxl))*100,2)
```

```{r}
library(seqinr)
library(gtools)
asc( s2c("DDDDCDEDCDDDDBBDDDCC@")) -33
```

# Section 4

```{r}
expr <- read.table("https://bioboot.github.io/bggn213_W19/class-material/rs8067378_ENSG00000172057.6.txt")

head(expr)
```

```{r}
summary(expr)
```

```{r}
inds <- (expr$geno == "G/G")
summary(expr[inds,]$exp)
hist(expr[inds,]$exp)
boxplot(expr[inds,]$exp)
```

```{r}
inds <- (expr$geno == "A/A")
summary(expr[inds,]$exp)
```

```{r}
inds <- (expr$geno == "A/G")
summary(expr[inds,]$exp)
```


First try at a boxplot to show this data

```{r}
# y ~ grp
boxplot(exp ~ geno , data=expr, notch=TRUE)
```






















