---
title: 'Class 6: R functions'
author: "Kellie Lemoine"
date: "April 19, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview
Today we will focus on **R functions** but we will start with a bit of **file reading**

```{r}
plot(1:10, type = "l", col="blue")
```

```{r}
read.table("test1.txt", header = TRUE, sep = ",")
```

```{r}
read.table("test2.txt", header = TRUE, sep = "$")
```

```{r}
read.table("test3.txt", header = FALSE)
```


```{r}
read.csv("https://bioboot.github.io/bggn213_S19/class-material/test2.txt", header = TRUE, sep = "$")
```


## Our first function

Add some numbers

```{r}
add <- function(x, y=1) {
  # the body
  x + y
}
```


```{r}
add(4)
```

```{r}
add(4, 5)
```

```{r}
add( c(1,3,5), 1)
```

```{r}
#add( 1, 3, 5)
```

```{r}
#add(x=1, y="barry")
```

## our 2nd example function

```{r}
rescale <- function(x) {
 rng <-range(x)
 (x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
rescale( c(1, 3, NA, 5, 10))
```

```{r}
x <- c(1, 3, NA, 5, 10)
rng <- range(x, na.rm = TRUE)
rng
 (x - rng[1]) / (rng[2] - rng[1])

```


```{r}
rescale(1:10)
```

```{r}
rescale2 <- function(x, na.rm = TRUE) {
 rng <-range(x, na.rm = na.rm)
 (x - rng[1]) / (rng[2] - rng[1])
}
```


```{r}
rescale2( c(1, 3, NA, 10) )
```


```{r}
rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {

 rng <-range(x, na.rm=TRUE)
 print("Hello")
 
 answer <- (x - rng[1]) / (rng[2] - rng[1])
 
 print("is it me you are looking for?")

 if(plot) {
   plot(answer, typ="b", lwd=4)
   print("Dont sing please")}
 
 print("I can see it in ...")
 return(answer)
}
```

```{r}
rescale3(1:10)
```


```{r}
rescale3( 1:10, plot = TRUE )
```


## section 1B of hands on worksheet

```{r}
#install.packages("bio3d")
```

```{r}
library(bio3d)
```


```{r}
s1 <- read.pdb("4AKE")
```

```{r}
s2 <- read.pdb("1AKE")
```

```{r}
s3 <- read.pdb("1E4Y")
```


```{r}
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s1.chainA
```


```{r}
s1.b <- s1.chainA$atom$b
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor") 
```


```{r}
plotb3(s1.b, typ="l", ylab="Bfactor") 
```


```{r}
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s3, chain="A", elety="CA")
s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```


```{r}
rbind(s1.b, s2.b, s3.b)
```

```{r}
cbind(s1.b, s2.b, s3.b)
```


```{r}
hc <- hclust( dist( rbind(s1.b, s2.b, s3.b) ) )
plot(hc)
```















